
services:
  twinsight:
    image: osrf/ros:humble-desktop-full
    container_name: twinsight_dev
    network_mode: host
    privileged: true  # Necessary for RPi 5 camera access
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0  # Change if working with multiple robots
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/vinh-le/LURA/TwinSight-digital-twin/turbopi_ros2:/home/ubuntu # Mounts your code
      - /dev:/dev  # Access to camera and peripherals
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
    restart: unless-stopped
